.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vericonomy_qt test_vericonomy_qt
clean: FORCE
	$(MAKE) -C .. vericonomy_qt_clean test_vericonomy_qt_clean
check: FORCE
	$(MAKE) -C .. test_vericonomy_qt_check
vericonomy-qt vericonomy-qt.exe: FORCE
	 $(MAKE) -C .. vericonomy_qt
